# Build manifest for sourcehut (https://builds.sr.ht/~gullik/gwm)
image: alpine/latest

packages:
  - cppcheck
  - libx11-dev

sources:
  - https://git.sr.ht/~gullik/gwm

tasks:
  - build: |
      cd gwm
      make
  - cppcheck: |
      cd gwm
      make cppcheck
